# https://www.appveyor.com/docs/lang/cpp/
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      JASL_VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JASL_VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat

install:
  - cinst python2
  - python.exe --version

build: off

test_script:
  - python .\build\build_helper.py --appveyor --msvc-vcvarsall-path "%JASL_VS%"