language: cpp

matrix:
  include:
    - os: linux
      env:
        - NAME=linux-clang 
        - GN_HASH=ed8b2bc0617fee4ebd1d1a35e8a5bc168c4ca874
        - NINJA_LINK=https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
      script:
        - python ./build/build_helper.py --travis-ci --compiler-type clang
    - os: linux
      env: 
        - NAME=linux-gcc
        - GN_HASH=ed8b2bc0617fee4ebd1d1a35e8a5bc168c4ca874
        - NINJA_LINK=https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
      script:
        - pip install --user cpp-coveralls
        - python ./build/build_helper.py --travis-ci --compiler-type gcc
      after_success:
        - coveralls --repo-token $COVERALLS_REPO_TOKEN --gcov-options '\-lp' -b out/asanF_cGcc_covT_debugT_defsE_perfF_std11_testsT
    - os: osx
      env: 
        - NAME=osx-clang
        - GN_HASH=a14b089cbae9c29ecbc781686ada8babac8550af
        - NINJA_LINK=https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-mac.zip
      script:
        - python ./build/build_helper.py --travis-ci --compiler-type clang

before_install:
  - mkdir bin
  - cd bin
  - wget -O gn https://storage.googleapis.com/chromium-gn/$GN_HASH
  - chmod +x gn
  - wget -O ninja.zip $NINJA_LINK
  - unzip ninja.zip
  - chmod +x ninja
  - PATH=$PATH:`pwd`
  - cd ..
  - gn --version
  - ninja --version
  - python --version
  - echo $PATH
