language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.6
            - clang-3.7
            - clang-3.8
      env: 
        - N=linux-clang
        - GN_HASH=ed8b2bc0617fee4ebd1d1a35e8a5bc168c4ca874
        - NINJA_LINK=https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
      script:
        - python ./build/build_helper.py --travis-ci --compiler-type clang
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-3.9
            - clang-4.0
            - clang-5.0
      env: 
        - N=linux-clang
        - GN_HASH=ed8b2bc0617fee4ebd1d1a35e8a5bc168c4ca874
        - NINJA_LINK=https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
      script:
        - python ./build/build_helper.py --travis-ci --compiler-type clang
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - g++-5
      env: 
        - N=linux-gcc
        - GN_HASH=ed8b2bc0617fee4ebd1d1a35e8a5bc168c4ca874
        - NINJA_LINK=https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
      script:
        - python ./build/build_helper.py --travis-ci --compiler-type gcc
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - g++-7
      env: 
        - N=linux-gcc
        - GN_HASH=ed8b2bc0617fee4ebd1d1a35e8a5bc168c4ca874
        - NINJA_LINK=https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
      script:
        - python ./build/build_helper.py --travis-ci --compiler-type gcc
      after_success:
        - pip install --user cpp-coveralls
        - gn gen out/coveralls --args="is_debug=true is_generate_test_coverage=true compiler_type=\"gcc\" std_version=\"c++11\""
        - ninja -C out/coveralls
        - coveralls -t $COVERALLS_REPO_TOKEN -e performance -e test -b out/coveralls
    - os: osx
      compiler: clang
      env: 
        - N=osx-clang
        - GN_HASH=a14b089cbae9c29ecbc781686ada8babac8550af
        - NINJA_LINK=https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-mac.zip
      script:
        - python ./build/build_helper.py --travis-ci --compiler-type clang

before_install:
  - mkdir bin
  - cd bin
  - wget -O gn https://storage.googleapis.com/chromium-gn/$GN_HASH
  - chmod +x gn
  - wget -O ninja.zip $NINJA_LINK
  - unzip ninja.zip
  - chmod +x ninja
  - PATH=$PATH:`pwd`
  - cd ..
  - gn --version
  - ninja --version
  - python --version
  - echo $PATH
  - ls -all /usr/bin/ | grep ++
